# can run locally with: "act --rm pull_request"
# see https://github.com/nektos/act

name: Regression
on: [workflow_dispatch, pull_request]

jobs:
  verilator:
    name: Verilator
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zeroasiccorp/sbtest:0.0.5
      credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.SGH_REPO_PAT }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.SGH_REPO_PAT }}
          submodules: recursive

      - name: Install Switchboard Python package
        run: |
          pip3 install -e .

      - name: Run Python binding test
        working-directory: examples/python
        run: |
          make > out.log
          cat out.log
          grep -Fxq "PASS!" out.log

      - name: Run Python binding test (UMI)
        working-directory: examples/umiram_python
        run: |
          make > out.log
          cat out.log
          grep -Fxq "PASS!" out.log

      - name: Run Icarus simulation
        working-directory: examples/minimal-icarus
        run: |
          make > out.log
          cat out.log
          grep -Fxq "PASS!" out.log

      - name: Run Verilator simulation
        working-directory: examples/riscv-grid
        run: |
          make hello > out.log
          cat out.log
          grep -Fxq "Hello World!" out.log

      - name: Run torture tests
        working-directory: tests
        run: |
          make torture > out.log
          cat out.log
          grep -Fxq "PASS" out.log

  fpga_sim:
    name: FPGA queue simulation
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zeroasiccorp/sbtest:0.0.5
      credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.SGH_REPO_PAT }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.SGH_REPO_PAT }}
          submodules: recursive

      - name: Run FPGA loopback simulation
        working-directory: examples/fpga-loopback
        run: |
          make test > out.log
          cat out.log
          grep -Fxq "PASS" out.log
