name: Regression test
on: [push, pull_request]

jobs:
  benchmark:
    name: Regression test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2

      - name: Build binary + run Spike simulation (in Docker)
        uses: addnab/docker-run-action@v3
        with:
          image: avidane/riscv-spike
          options: -v ${{ github.workspace }}:/work -w /work
          run: |
            make -C firmware firmware.bin
            make spike > out-spike-sim.log
            cat out-spike-sim.log

      - name: Check Spike simulation
        run: |
          grep -Fxq "Hello World from core 0!" out-spike-sim.log

      - name: Install RTL simulation prerequisites
        run: |
          pip3 install fusesoc
          sudo apt-get install verilator

      - name: Run RTL simulation
        run: |
          make
          make run > tee out-rtl-sim.log
          cat out-rtl-sim.log
          grep -Fxq "Hello World from core 0!" out-rtl-sim.log
          grep -Fxq "ALL TESTS PASSED." out-rtl-sim.log
