name: Regression test
on: pull_request

jobs:
  benchmark:
    name: Regression test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install prerequisites
        run: |
          pip3 install fusesoc && \
          sudo apt-get install verilator gcc-riscv64-unknown-elf binutils-riscv64-unknown-elf
      - name: Build firmware and simulator
        run: make
      - name: Run QEMU simulation
        run: set -o pipefail && make -C firmware qemu | tee out-qemu-sim.log
      - name: Check QEMU simulation results
        run: |
          grep -Fxq "Hello World!" out-qemu-sim.log
      - name: Run RTL simulation
        run: set -o pipefail && make run | tee out-rtl-sim.log
      - name: Check RTL simulation results
        run: |
          grep -Fxq "Hello World!" out-rtl-sim.log && \
          grep -Fxq "ALL TESTS PASSED." out-rtl-sim.log
