name: Regression test
on: [push, pull_request]

jobs:
  benchmark:
    name: Regression test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Install prerequisites
        run: |
          pip3 install fusesoc && \
          sudo apt-get install verilator gcc-riscv64-unknown-elf binutils-riscv64-unknown-elf qemu-system-misc
      - name: Build firmware and simulator
        run: make
#      - name: Run QEMU simulation
#        run: set -o pipefail && make -C firmware qemu | tee out-qemu-sim.log
#      - name: Check QEMU simulation results
#        run: |
#          grep -Fxq "Hello World!" out-qemu-sim.log
      - name: Install Spike
        run: |
          wget https://github.com/zeroasiccorp/interposer-verif/releases/download/tools/spike-1.1.0-ubuntu-22.04.tar.gz && \
          tar xzvf spike-1.1.0-ubuntu-22.04.tar.gz && \
          sudo mv spike /usr/local/bin/spike
      - name: Run Spike simulation
        run: set -o pipefail && make -C firmware spike | tee out-spike-sim.log
      - name: Check Spike simulation results
        run: |
          grep -Fxq "Hello World from core 0!" out-spike-sim.log
      - name: Run RTL simulation
        run: set -o pipefail && make run | tee out-rtl-sim.log
      - name: Check RTL simulation results
        run: |
          grep -Fxq "Hello World from core 0!" out-rtl-sim.log && \
          grep -Fxq "ALL TESTS PASSED." out-rtl-sim.log
