# can run locally with: "act --rm pull_request"
# see https://github.com/nektos/act

name: Regression
on: [pull_request]

jobs:
  verilator:
    name: Verilator
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install prerequisites
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            verilator \
            gcc-riscv64-unknown-elf \
            binutils-riscv64-unknown-elf \
            libboost-dev \
            libboost-system-dev

      - name: Run RTL simulation
        working-directory: examples/riscv-grid
        run: |
          make hello > out.log
          cat out.log
          grep -Fxq "Hello World!" out.log
