# can run locally with: "act --rm pull_request"
# see https://github.com/nektos/act

name: Regression
on: [pull_request]

# TODO: consider creating a Docker image that has all tools,
# instead of using an existing image for Spike, and installing
# other tools via apt-get

jobs:
  spike:
    name: Spike
    runs-on: ubuntu-latest
    container: avidane/riscv-spike
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Spike simulation
        run: |
          sed -i 's/archive.ubuntu.com/old-releases.ubuntu.com/g' /etc/apt/sources.list

          apt-get update -y
          apt-get install -y python3 python3-pip

          python3 -m pip install -e .

          cd interposer/verif && python3 verif.py spike

  verilator:
    name: Verilator
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Verilator simulation
        run: |
          sudo apt-get update -y
          sudo apt-get install -y python3-pip verilator gcc-riscv64-unknown-elf binutils-riscv64-unknown-elf

          python3 -m pip install -e .

          cd interposer/verif && python3 verif.py verilator