name: Regression
on: [push, pull_request]

jobs:
  benchmark:
    name: Regression
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2

      - name: Build binary + run Spike simulation (in Docker)
        run: |
          docker run --rm -v $(pwd):/work -w /work avidane/riscv-spike "make -C firmware firmware.bin && make spike > out-spike-sim.log"
          cat out-spike-sim.log

      - name: Check Spike simulation
        run: |
          grep -Fxq "Hello World from core 0!" out-spike-sim.log

      - name: Install RTL simulation prerequisites
        run: |
          sudo apt-get update -y
          sudo apt-get install -y python3-pip verilator
          python3 -m pip install fusesoc

      - name: Run RTL simulation
        run: |
          make run > out-rtl-sim.log
          cat out-rtl-sim.log
          grep -Fxq "Hello World from core 0!" out-rtl-sim.log
          grep -Fxq "ALL TESTS PASSED." out-rtl-sim.log
