# can run locally with: "act --rm pull_request"
# see https://github.com/nektos/act

name: Regression
on: [pull_request]

jobs:
  verilator:
    name: Verilator
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
        with:
          #ssh-key: ${{ secrets.SSH_KEY_FOR_UMI }}
          token: ${{ secrets.SGH_REPO_PAT }}
          submodules: recursive
      - name: Install prerequisites
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            verilator \
            iverilog \
            gcc-riscv64-unknown-elf \
            binutils-riscv64-unknown-elf

      - name: Run Icarus simulation
        working-directory: examples/minimal-icarus
        run: |
          make > out.log
          cat out.log
          grep -Fxq "PASS!" out.log

      - name: Run Verilator simulation
        working-directory: examples/riscv-grid
        run: |
          make hello > out.log
          cat out.log
          grep -Fxq "Hello World!" out.log
