name: Regression test
on: [push, pull_request]

jobs:
  benchmark:
    name: Regression test
    runs-on: ubuntu-latest
    container: avidane/riscv-spike
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2

      - name: Install prerequisites
        # TODO: consider building a docker image that has this already?
        run: |
          apt-get update -y
          apt-get install -y verilator python3
          pip3 install fusesoc

      - name: Run Spike simulation
        run: |
          set -o pipefail && make spike | tee out-spike-sim.log
          grep -Fxq "Hello World from core 0!" out-spike-sim.log

      - name: Build RTL simulator
        run: make

      - name: Run RTL simulation
        run: |
          make
          set -o pipefail && make run | tee out-rtl-sim.log
          grep -Fxq "Hello World from core 0!" out-rtl-sim.log && \
          grep -Fxq "ALL TESTS PASSED." out-rtl-sim.log
