# can run locally with: "act --rm pull_request"
# see https://github.com/nektos/act

name: Regression
on: [pull_request]

# TODO: consider creating a Docker image that has all tools,
# instead of using an existing image for Spike, and installing
# other tools via apt-get

# reference for editing apt sources: https://askubuntu.com/a/91821

jobs:
  spike:
    name: Spike
    runs-on: ubuntu-latest
    container: avidane/riscv-spike
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Spike simulation
        run: |
          sed -i -re 's/([a-z]{2}\.)?archive.ubuntu.com|security.ubuntu.com/old-releases.ubuntu.com/g' /etc/apt/sources.list

          apt-get update -y
          apt-get install -y python3 python3-pip

          python3 -m pip install -e .

          cd interposer/verif && python3 verif.py spike

  zmq:
    name: ZMQ
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Verilator simulation
        run: |
          sudo apt-get update -y
          sudo apt-get install -y python3-pip verilator gcc-riscv64-unknown-elf binutils-riscv64-unknown-elf libzmq3-dev iverilog

          python3 -m pip install -e .

          cd interposer/verif

          cd cocotb
          make &
          PYTEST_PID=$!
          cd ..
          python3 verif.py zmq:hello
          kill $PYTEST_PID

          python3 verif.py verilator &
          VERILATOR_PID=$!
          python3 verif.py zmq
          kill $VERILATOR_PID

  sc_spike:
    name: Spike (thru SC)
    runs-on: ubuntu-latest
    container: avidane/riscv-spike
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Spike simulation
        run: |
          sed -i -re 's/([a-z]{2}\.)?archive.ubuntu.com|security.ubuntu.com/old-releases.ubuntu.com/g' /etc/apt/sources.list

          apt-get update -y
          apt-get install -y python3 python3-pip

          python3 -m pip install --upgrade pip
          python3 -m pip install siliconcompiler==0.9.1
          python3 -m pip install -e .

          cd interposer && python3 picorv32.py verify --tool spike

  sc_verilator:
    name: Verilator (thru SC)
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Verilator simulation
        run: |
          sudo apt-get update -y
          sudo apt-get install -y python3-pip verilator gcc-riscv64-unknown-elf binutils-riscv64-unknown-elf

          python3 -m pip install --upgrade pip
          python3 -m pip install siliconcompiler==0.9.1
          python3 -m pip install -e .

          cd interposer && python3 picorv32.py verify --tool verilator
